config/routes.rb
Rails.application.routes.draw do
  resources :tutoring_times
  resources :coaches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#welcome"
  get '/students', to: 'students#index', as: 'students'
  get '/students/new', to: 'students#new', as: 'new_student'
  post '/students', to: 'students#create'
  get '/students/:id', to: 'students#show', as: 'student'
  get '/students/:id/edit', to: 'students#edit'
  patch '/students/:id', to: 'students#update'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
    has_many :tutoring_times
    has_many :students, through: :tutoring_times
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :tutoring_times
    has_many :coaches, through: :tutoring_times
end

app/models/tutoring_time.rb
class TutoringTime < ApplicationRecord
  belongs_to :student
  belongs_to :coach

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome
    end 
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
    def index 
        @coaches = Coach.all 
    end 

    def show 
        @coach = Coach.find(params[:id])
    end 

    def new
        @coach = Coach.new 
    end 

    def create
        @coach = Coach.create(coach_params)
        redirect_to coach_path(@coach)
    end 

    def edit
        @coach = Coach.find(params[:id])
    end 

    def update
        @coach = Coach.find(params[:id])
        @coach.update(coach_params)
        redirect_to coach_path(@coach)
    end


    private 
    def coach_params
        params.require(:coach).permit(:name, :experience_years)
    end 
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index 
        @students = Student.all 
    end 

    def show 
        @student = Student.find(params[:id])
    end 

    def new
        @student = Student.new 
    end 

    def create
        @student = Student.create(student_params)
        redirect_to student_path(@student)
    end 

    def edit
        @student = Student.find(params[:id])
    end 

    def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to student_path(@student)
    end

    def delete
    end 

    private 
    def student_params
        params.require(:student).permit(:name, :age, :language)
    end 
end

app/controllers/tutoring_times_controller.rb
class TutoringTimesController < ApplicationController
    def index 
        @tutoring_times = TutoringTime.all 
    end 

    def show 
        @tutoring_time = TutoringTime.find(params[:id])
    end 

    def new
        @tutoring_time = TutoringTime.new 
        @students = Student.all
        @coaches = Coach.all
    end 

    def create
        @tutoring_time = TutoringTime.create(tutoring_params)        
        student = Student.find(tutoring_params[:student_id])
        redirect_to student_path(student)
    end 

    def edit
        @tutoring_time= TutoringTime.find(params[:id])
        @students = Student.all
        @coaches = Coach.all
    end 

    def update
        @tutoring_time = TutoringTime.find(params[:id])
        @tutoring_time.update(tutoring_params)
        redirect_to tutoring_time_path(@tutoring_time)
    end

    def destroy
        @tutoring_time = TutoringTime.destroy(params[:id])
        redirect_to tutoring_times_path
    end 

    private 
    def tutoring_params
        params.require(:tutoring_time).permit(:appointment_time, :student_id, :coach_id)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tutoring_times_helper.rb
module TutoringTimesHelper
end

app/views/application/welcome.html.erb
<div class='content'>
    <h1>Welcome to Tutoring Time at Avatar School</h1>

    <img style="display: block; margin:0 auto; width: 50%;"src="https://cdn.vox-cdn.com/thumbor/mXo5ObKpTbHYi9YslBy6YhfedT4=/95x601:1280x1460/1200x800/filters:focal(538x858:742x1062)/cdn.vox-cdn.com/uploads/chorus_image/image/66699060/mgidarccontentnick.comc008fa9d_d.0.png" >
    <br>
        <h2>Where would you like to start?</h2>
    
        <span class=button><%= link_to "STUDENTS PORTAL", students_path %></span><br><br><br>
        <span class=button><%= link_to "COACHES PORTAL", coaches_path %></span><br><br><br>
        <span class=button><%= link_to "TUTORING SESSION", tutoring_times_path %></span>
    
</div>

app/views/coaches/edit.html.erb
<h1> Update Coach Form</h1>

<%= form_for @coach do |f| %>
<%= f.label :name %>
<%= f.text_field :name %> 
<%= f.label :experience_years %>
<%= f.number_field :experience_years %><br><br>
<%=f.submit "Update Coach" %>
<% end %>

app/views/coaches/index.html.erb
<div class='content'>
<h1> Welcome Coaches</h1>

    <p><% @coaches.map do |coach_info| %>
    Coach Name: <strong><%=link_to coach_info.name, coach_path(coach_info) %></strong>
    - Years of Experience: <strong><%=coach_info.experience_years %></strong></p> 
    <% end %>

    <br><br>
    <span class='button'> <%=link_to 'ADD A NEW COACH', new_coach_path %></span>

</div>

app/views/coaches/new.html.erb
<div class='content'>
    <h1> New Coach Form</h1>

    <%= form_for @coach do |f| %>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %> 
    <%= f.label :experience_years, "Years of Experience" %>
    <%= f.number_field :experience_years %><br><br>
    <%=f.submit "New Coach" %>
    <% end %>
</div>

app/views/coaches/show.html.erb
<div class='content'>
    <h1> Information about <%=@coach.name %></h1>
    <p>Years of Experience: <%= @coach.experience_years %></p>

    <br><br>
    <span class='button'><%=link_to "EDIT", edit_coach_path %></span><br><br><br>
    <span class='button'><%=link_to "GO BACK", coaches_path %></span>

    <br><br><br>
    <% if @coach.tutoring_times.count > 0 %>
        <h2>List of appointments</h2>
        <br>
        <p><% @coach.tutoring_times.map do |session| %>
        On: <strong><%= link_to session.appointment_time, tutoring_time_path(session) %></strong> - 
        with <strong><%= session.student.name %></strong> - 
        On <strong><%= session.student.language %> </strong> language </p>
        <% end %>
    <% else %>
    <h2>This coach has no appointments at this moment</h2>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TutoringSession</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<div class='content'>
    <h1> Update Student Form</h1>

    <%= form_for @student do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> 
    <%= f.label :language %>
    <%= f.text_field :language %>
    <%= f.label :age %>
    <%= f.number_field :age %> <br><br>
    <%=f.submit "Update Student" %>
    <% end %>
</div>

app/views/students/index.html.erb
<div class='content'>
    <h1> List of current Students</h1>

    <% @students.map do |student_info| %>
    <p>Student Name: <strong><%=link_to student_info.name, student_path(student_info) %></strong>
    - Language: <strong><%=student_info.language %></strong> </p> 
    <% end %>
        <br><br><br>
    <span class='button'><%= link_to "Create a New Student", new_student_path %></span>

</div>

app/views/students/new.html.erb
<div class='content'>
    <h1> New Student Form</h1>

    <%= form_for @student do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> 
    <%= f.label :language %>
    <%= f.text_field :language %>
    <%= f.label :age %>
    <%= f.number_field :age %> <br><br>
    <%=f.submit "New Student" %>
    <% end %>

</div>

app/views/students/show.html.erb
<div class='content'>
    <h1><%=@student.name %>'s page</h1>

    <p>Language: <strong><%= @student.language %></strong></p>
    <p>Age: <%= @student.age %></p>
    <% if @student.tutoring_times.count > 0 %>
        <h2>Upcoming appointments</h2>
            <p><% @student.tutoring_times.map do |session| %>
                <%= link_to session.id, tutoring_time_path(session.id) %>.
                Coach: <strong><%= link_to session.coach.name, coach_path(session.coach)%></strong> - 
                Date and Time: <strong><%= session.appointment_time %></strong></p>
            <% end %>
        <% else %>
        <p> Current Student has no appointments booked yet</p>
        <% end %>
        <br><br>
        <span class='button'> <%=link_to "CREATE A TUTORING SESSION", new_tutoring_time_path %></span>
</div>

app/views/tutoring_times/edit.html.erb
<div class='content'>
    <h1> Update Session</h1>

    <%= form_for @tutoring_time do |f| %>
    <%= f.label :student_id, "Student" %>
    <%= f.collection_select :student_id, @students, :id, :name %> 
    <%= f.label :coach_id, "Coach" %>
    <%= f.collection_select :coach_id, @coaches, :id, :name %> 
    <%= f.label :appointment_time %>
    <%= f.datetime_select :appointment_time %>

    <%=f.submit %>
    <% end %>
</div>

app/views/tutoring_times/index.html.erb
<div class='content'>
<h1> Tutoring Sessions List</h1>

    <p> <% @tutoring_times.map do |tutoring_info| %>
        
        Date: <%= link_to tutoring_info.appointment_time, tutoring_time_path(tutoring_info) %> <br>
        Coach: <%=tutoring_info.coach.name %> <br>
        Student: <%=tutoring_info.student.name %> <br>
        On <%=tutoring_info.student.language %> language <br>
    </p>
    <br>
    <% end %>
    <br><br>
    <span class='button'> <%=link_to 'GO BACK', "/" %></span>

</div>

app/views/tutoring_times/new.html.erb
<div class='content'>
    <h1> Tutoring Session</h1>

    <%= form_for @tutoring_time do |f| %>
    <%= f.label :student_id, "Student" %>
    <%= f.collection_select :student_id, @students, :id, :name %> 
    <%= f.label :coach_id, "Coach" %>
    <%= f.collection_select :coach_id, @coaches, :id, :name %> 
    <%= f.label :appointment_time %>
    <%= f.datetime_select :appointment_time %>

    <%=f.submit "New Session" %>
    <% end %>
    </div>

app/views/tutoring_times/show.html.erb
<div class='content'>
    <h1> Tutoring Session for <%=@tutoring_time.student.name %> </h1>


    <p>
        Date: <strong><%=@tutoring_time.appointment_time %></strong> <br>
        Coach: <strong><%=@tutoring_time.coach.name %></strong> <br>
        Student: <strong><%=@tutoring_time.student.name %></strong> <br>
        On <strong><%=@tutoring_time.student.language %></strong> language <br>
    </p>
    <br><br>
    <span class='button'> <%=link_to "EDIT", edit_tutoring_time_path %></span><br><br><br>
    <span class='button'> <%=link_to "DELETE", @tutoring_time, :method => :delete %></span><br><br><br>
    <span class='button'> <%=link_to "GO TO STUDENT'S PAGE", student_path(@tutoring_time.student) %></span><br><br><br>
    <span class='button'> <%=link_to "GO TO COACH'S PAGE", coach_path(@tutoring_time.coach) %></span>


</div>